// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Create(arg1:main.ConjuntoRif):Promise<{[key: string]: any}>;

export function GetAll():Promise<Array<main.ConjuntoRif>>;

export function Reset():Promise<{[key: string]: any}>;

export function Update(arg1:number,arg2:main.ConjuntoRif):Promise<{[key: string]: any}>;
