// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['ConjuntoRif']['Create'](arg1);
}

export function GetAll() {
  return window['go']['main']['ConjuntoRif']['GetAll']();
}

export function Reset() {
  return window['go']['main']['ConjuntoRif']['Reset']();
}

export function Update(arg1, arg2) {
  return window['go']['main']['ConjuntoRif']['Update'](arg1, arg2);
}
