// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Create(arg1:main.Empresa):Promise<{[key: string]: any}>;

export function Delete(arg1:number):Promise<{[key: string]: any}>;

export function GetAll():Promise<Array<main.Empresa>>;

export function Update(arg1:number,arg2:main.Empresa):Promise<{[key: string]: any}>;
