// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['Empresa']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['Empresa']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['main']['Empresa']['GetAll']();
}

export function GetAllByConjuntoRif(arg1, arg2) {
  return window['go']['main']['Empresa']['GetAllByConjuntoRif'](arg1, arg2);
}

export function GetAllByTerminalRif(arg1) {
  return window['go']['main']['Empresa']['GetAllByTerminalRif'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['main']['Empresa']['Update'](arg1, arg2);
}
