// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Assign(arg1:number,arg2:number,arg3:Array<main.Impuesto>):Promise<{[key: string]: any}>;

export function DeleteAllFromQuincena(arg1:number):Promise<{[key: string]: any}>;

export function GetAll(arg1:number):Promise<Array<main.Impuesto>>;
