// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Assign(arg1, arg2, arg3) {
  return window['go']['main']['Impuesto']['Assign'](arg1, arg2, arg3);
}

export function DeleteAllFromQuincena(arg1) {
  return window['go']['main']['Impuesto']['DeleteAllFromQuincena'](arg1);
}

export function GetAll(arg1) {
  return window['go']['main']['Impuesto']['GetAll'](arg1);
}
