// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Assign(arg1, arg2) {
  return window['go']['main']['Liquidacion']['Assign'](arg1, arg2);
}

export function DeleteAll() {
  return window['go']['main']['Liquidacion']['DeleteAll']();
}

export function GetAll() {
  return window['go']['main']['Liquidacion']['GetAll']();
}
