// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Assign(arg1:number,arg2:Array<main.Liquidacion>):Promise<{[key: string]: any}>;

export function DeleteAll():Promise<{[key: string]: any}>;

export function GetAll():Promise<Array<main.Liquidacion>>;
